version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mango_data:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}





  web:
    build: ./app
    ports:
      - "8080:5000"
#    volumes:
#      - ./app:/app
    links:
      - mongodb
    env_file:
      - ./.env
    depends_on:
      - mongodb
    command: python app.py

volumes:
  mango_data:
